### ISSUE TITLE
modify_form function is not working on version 1.7.x

### ISSUE THREAD

**Issue by daviedR** [siteorigin/so-widgets-bundle#329]
Hi guys,

I have custom widgets that use `modify_form` function to populate additional attributes to the form options. I noticed, since version 1.7 the filter doesn't work anymore. Is it a bug? Or does it need different implementation?

Regards

**Comment by AlexGStapleton** [comment]
modify_form() doesn't look to have been adjusted in over a year. Could you please provide an example of what you using modifiy_form so I can run a few tests?

**Comment by daviedR** [comment]
You can use this widget class to test.

```
<?php
/*
Widget Name: CUSTOM Widget Test
Description: Test modify_form.
Author: David Rozando
Author URI: 
*/

class Custom_SiteOrigin_Widget_Test extends SiteOrigin_Widget {
	function __construct() {
		parent::__construct(
			'custom-sow-test',
			esc_html__( 'CUSTOM Widget Test', 'test' ),
			array(
				'description' => esc_html__( 'Test modify_form.', 'test' ),
			),
			array(
				
			),
			array(
				'post_ids' => array(
					'type' => 'select',
					'label' => esc_html__( 'Select posts', 'test' ),
				),
			),
			plugin_dir_path( __FILE__ )
		);
	}

	function modify_form( $form ) {
		$posts = get_posts( array(
			'post_type' => 'post',
			'orderby' => 'title',
			'order' => 'asc',
			'posts_per_page' => -1,
		) );

		$post_ids = array();

		foreach ( $posts as $p ) {
			$post_ids[ $p->ID ] = $p->post_title;
		}

		$form['post_ids']['options'] = $post_ids;

		return $form;
	}
}

siteorigin_widget_register( 'custom-sow-test', __FILE__, 'Custom_SiteOrigin_Widget_Test' );
```

You should add the widget folder initialisation by yourself, and then activate the widget. The idea is to populate all post IDs into the select box field. Tried to `var_dump` the `$form` variable inside `modify_form` but it's not printed on the screen. Looks like the `modify_form` is not being called at all.

**Comment by AlexGStapleton** [comment]
modify_form is only run if you don't specify form options ([ref](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/siteorigin-widget.class.php#L373)).

To clarify, why not use the [posts form field](https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-posts)?

**Comment by gregpriday** [comment]
This might actually be an unintended change. The original intention was for `modify_form` to always run at least once. I'll take a look at this.

**Comment by daviedR** [comment]
Hi @AlexGStapleton, I thought `modify_form` is called to modify the form options declared on __construct() not as a fallback function.

The class above is just for test, I need to have different select fields which involve various custom options from my own theme. That's why I need the `modify_form` function to use my own query and populate the options into the fields.

Thanks @gregpriday, it worked on v1.6.5 (tested) but broken since v1.7.

**Comment by venkatraj** [comment]
I too have same problem. I need to modify_form to create a dropdown of custom taxonomy.
Since it is not available at `widgets_init` I need to do this at later stage.
I've even tried following simple class and it is not working
`<?php
/*
Widget Name: Alert
Description: todo
Author: N. Venkat Raj
Author URI: todo
Widget URI: todo
Video URI: todo
*/
class TS_Alert_Widget extends SiteOrigin_Widget {

	function __construct() {

		parent::__construct(

		// The unique id for your widget.
			'ts-alert-widget',

			// The name of the widget for display purposes.
			__('Alert', 'twentysixteen'),

			array(
				'description' => __('Creates an alert. It can be success, error, info alerts.', 'twentysixteen'),
			),

			//The $control_options array, which is passed through to WP_Widget
			array(
			),

			$form_options = array(
				'type' => array(
					'type' => 'select',
					'label' => __( 'Type of alert', 'twentysixteen' ),
					'default' => 'notice',
					'options' => array(),
				),
				'close' => array(
					'type' => 'select',
					'label' => __( 'Need close option?', 'twentysixteen' ),
					'default' => 'yes',
					'options' => array(
						'yes' => __( 'Yes', 'twentysixteen' ),
						'no' => __( 'No', 'twentysixteen' ),
					)
				),
				'content' => array(
					'type' => 'tinymce',
					'label' => __( 'Content.', 'twentysixteen' ),
					'rows' => 5,
				),
			)
		);
	}

	function modify_form( $form ) {
		$form['type']['options'] = array(
			'notice' => __( 'Notice', 'twentysixteen' ),
			'warning' => __( 'Warning', 'twentysixteen' ),
			'success' => __( 'Success', 'twentysixteen' ),
			'error' => __( 'Error', 'twentysixteen' ),
			'info' => __( 'Info', 'twentysixteen' ),
		);
		return $form;
	}

	function get_template_name($instance) {
		return 'default';
	}

	function get_template_variables( $instance, $args ) {
		return array(
			'type' => $instance['type'],
			'close' => $instance['close'],
			'content' => $instance['content']
		);
	}

	function get_style_name($instance) {
		return '';
	}

} // class TS_Alert_Widget

siteorigin_widget_register('ts-alert-widget', __FILE__, 'TS_Alert_Widget');`

**Comment by daviedR** [comment]
Is there any update on this? This is quite critical issue

**Comment by gregpriday** [comment]
I'll take a look at this in a little bit. That said, you could also migrate to the system that we're using more often in our own widgets.

We're using a [get_widget_form](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/icon/icon.php#L26) function that is only called when the form is needed. So the form isn't initialized on initializing the widget. This is a lot more efficient.

**Comment by gregpriday** [comment]
Hi @daviedR, this should be resolved in https://github.com/siteorigin/so-widgets-bundle/commit/cf27811652719901399404d15de0718f0a26c45a - if you have a chance, could you double check this for me?

**Comment by daviedR** [comment]
Hi @gregpriday 

Just tried version 1.7.2 but somehow it is still not working.

As you suggested, I have moved to `get_widget_form` function which looks like working well.

**Comment by braamgenis** [comment]
The issue seems to be resolved so closing. The current implementation preference is to use `get_widget_form` instead of passing `form_options` to the constructor, as this is what results in `modify_form` not being called later. We should perhaps mark the `form_options` constructor argument as deprecated.

**Comment by derpoho** [comment]
I know this is closed, but you should update the developer docs to show the preferred way. It was a long search to come here and see the solution to the not working `modify_form`

https://siteorigin.com/docs/widgets-bundle/form-building/modifying-forms/

Thanks!

**Comment by abooker819** [comment]
@AlexGStapleton people don't want to use the posts form field because who can remember all the categories they would need to type in? I'm trying to extend a staff widget I already have because I need two windows open just to see which category to type for the row, which is counterproductive. You guys don't give much documentation for queries on the form end, but I'm sure so many people would appreciate if you all added this autonomous feature for categories.

**Comment by AlexGStapleton** [comment]
The Posts form field provides a method for selecting categories via the Taxonomies field. Click the taxonomies field and a small box will appear that will allow for you to search for and select categories automatically - there's no need to remember anything about the category but the name.
